package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarreraEstudianteId generated by hbm2java
 */
@Embeddable
public class CarreraEstudianteId  implements java.io.Serializable {


     private int codCarrera;
     private int usuRut;

    public CarreraEstudianteId() {
    }

    public CarreraEstudianteId(int codCarrera, int usuRut) {
       this.codCarrera = codCarrera;
       this.usuRut = usuRut;
    }
   


    @Column(name="cod_carrera", nullable=false)
    public int getCodCarrera() {
        return this.codCarrera;
    }
    
    public void setCodCarrera(int codCarrera) {
        this.codCarrera = codCarrera;
    }


    @Column(name="usu_rut", nullable=false)
    public int getUsuRut() {
        return this.usuRut;
    }
    
    public void setUsuRut(int usuRut) {
        this.usuRut = usuRut;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CarreraEstudianteId) ) return false;
		 CarreraEstudianteId castOther = ( CarreraEstudianteId ) other; 
         
		 return (this.getCodCarrera()==castOther.getCodCarrera())
 && (this.getUsuRut()==castOther.getUsuRut());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodCarrera();
         result = 37 * result + this.getUsuRut();
         return result;
   }   


}


