package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InscripcionAsignatura generated by hbm2java
 */
@Entity
@Table(name="inscripcion_asignatura"
    ,catalog="navegadorcitodb"
)
public class InscripcionAsignatura  implements java.io.Serializable {


     private InscripcionAsignaturaId id;
     private String estAprobado;
     private String estInscripcion;

    public InscripcionAsignatura() {
    }

    public InscripcionAsignatura(InscripcionAsignaturaId id, String estAprobado, String estInscripcion) {
       this.id = id;
       this.estAprobado = estAprobado;
       this.estInscripcion = estInscripcion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="insAño", column=@Column(name="ins_año", nullable=false) ), 
        @AttributeOverride(name="insSemestre", column=@Column(name="ins_semestre", nullable=false) ), 
        @AttributeOverride(name="insParalelo", column=@Column(name="ins_paralelo", nullable=false) ), 
        @AttributeOverride(name="codAsign", column=@Column(name="cod_asign", nullable=false) ), 
        @AttributeOverride(name="usuRut", column=@Column(name="usu_rut", nullable=false) ) } )
    public InscripcionAsignaturaId getId() {
        return this.id;
    }
    
    public void setId(InscripcionAsignaturaId id) {
        this.id = id;
    }

    
    @Column(name="est_aprobado", nullable=false, length=20)
    public String getEstAprobado() {
        return this.estAprobado;
    }
    
    public void setEstAprobado(String estAprobado) {
        this.estAprobado = estAprobado;
    }

    
    @Column(name="est_inscripcion", nullable=false, length=20)
    public String getEstInscripcion() {
        return this.estInscripcion;
    }
    
    public void setEstInscripcion(String estInscripcion) {
        this.estInscripcion = estInscripcion;
    }




}


