package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InscripcionAsignaturaId generated by hbm2java
 */
@Embeddable
public class InscripcionAsignaturaId  implements java.io.Serializable {


     private int insAño;
     private int insSemestre;
     private int insParalelo;
     private int codAsign;
     private int usuRut;

    public InscripcionAsignaturaId() {
    }

    public InscripcionAsignaturaId(int insAño, int insSemestre, int insParalelo, int codAsign, int usuRut) {
       this.insAño = insAño;
       this.insSemestre = insSemestre;
       this.insParalelo = insParalelo;
       this.codAsign = codAsign;
       this.usuRut = usuRut;
    }
   


    @Column(name="ins_año", nullable=false)
    public int getInsAño() {
        return this.insAño;
    }
    
    public void setInsAño(int insAño) {
        this.insAño = insAño;
    }


    @Column(name="ins_semestre", nullable=false)
    public int getInsSemestre() {
        return this.insSemestre;
    }
    
    public void setInsSemestre(int insSemestre) {
        this.insSemestre = insSemestre;
    }


    @Column(name="ins_paralelo", nullable=false)
    public int getInsParalelo() {
        return this.insParalelo;
    }
    
    public void setInsParalelo(int insParalelo) {
        this.insParalelo = insParalelo;
    }


    @Column(name="cod_asign", nullable=false)
    public int getCodAsign() {
        return this.codAsign;
    }
    
    public void setCodAsign(int codAsign) {
        this.codAsign = codAsign;
    }


    @Column(name="usu_rut", nullable=false)
    public int getUsuRut() {
        return this.usuRut;
    }
    
    public void setUsuRut(int usuRut) {
        this.usuRut = usuRut;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InscripcionAsignaturaId) ) return false;
		 InscripcionAsignaturaId castOther = ( InscripcionAsignaturaId ) other; 
         
		 return (this.getInsAño()==castOther.getInsAño())
 && (this.getInsSemestre()==castOther.getInsSemestre())
 && (this.getInsParalelo()==castOther.getInsParalelo())
 && (this.getCodAsign()==castOther.getCodAsign())
 && (this.getUsuRut()==castOther.getUsuRut());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInsAño();
         result = 37 * result + this.getInsSemestre();
         result = 37 * result + this.getInsParalelo();
         result = 37 * result + this.getCodAsign();
         result = 37 * result + this.getUsuRut();
         return result;
   }   


}


