package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MallaCurricularId generated by hbm2java
 */
@Embeddable
public class MallaCurricularId  implements java.io.Serializable {


     private int codPlan;
     private int codCarrera;
     private int codAsign;

    public MallaCurricularId() {
    }

    public MallaCurricularId(int codPlan, int codCarrera, int codAsign) {
       this.codPlan = codPlan;
       this.codCarrera = codCarrera;
       this.codAsign = codAsign;
    }
   


    @Column(name="cod_plan", nullable=false)
    public int getCodPlan() {
        return this.codPlan;
    }
    
    public void setCodPlan(int codPlan) {
        this.codPlan = codPlan;
    }


    @Column(name="cod_carrera", nullable=false)
    public int getCodCarrera() {
        return this.codCarrera;
    }
    
    public void setCodCarrera(int codCarrera) {
        this.codCarrera = codCarrera;
    }


    @Column(name="cod_asign", nullable=false)
    public int getCodAsign() {
        return this.codAsign;
    }
    
    public void setCodAsign(int codAsign) {
        this.codAsign = codAsign;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MallaCurricularId) ) return false;
		 MallaCurricularId castOther = ( MallaCurricularId ) other; 
         
		 return (this.getCodPlan()==castOther.getCodPlan())
 && (this.getCodCarrera()==castOther.getCodCarrera())
 && (this.getCodAsign()==castOther.getCodAsign());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodPlan();
         result = 37 * result + this.getCodCarrera();
         result = 37 * result + this.getCodAsign();
         return result;
   }   


}


