package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Matricula generated by hbm2java
 */
@Entity
@Table(name="matricula"
    ,catalog="navegadorcitodb"
)
public class Matricula  implements java.io.Serializable {


     private MatriculaId id;

    public Matricula() {
    }

    public Matricula(MatriculaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="matAño", column=@Column(name="mat_año", nullable=false) ), 
        @AttributeOverride(name="matSemestre", column=@Column(name="mat_semestre", nullable=false) ), 
        @AttributeOverride(name="codCarrera", column=@Column(name="cod_carrera", nullable=false) ), 
        @AttributeOverride(name="usuRut", column=@Column(name="usu_rut", nullable=false) ) } )
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }




}


