package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MatriculaId generated by hbm2java
 */
@Embeddable
public class MatriculaId  implements java.io.Serializable {


     private int matAño;
     private int matSemestre;
     private int codCarrera;
     private int usuRut;

    public MatriculaId() {
    }

    public MatriculaId(int matAño, int matSemestre, int codCarrera, int usuRut) {
       this.matAño = matAño;
       this.matSemestre = matSemestre;
       this.codCarrera = codCarrera;
       this.usuRut = usuRut;
    }
   


    @Column(name="mat_año", nullable=false)
    public int getMatAño() {
        return this.matAño;
    }
    
    public void setMatAño(int matAño) {
        this.matAño = matAño;
    }


    @Column(name="mat_semestre", nullable=false)
    public int getMatSemestre() {
        return this.matSemestre;
    }
    
    public void setMatSemestre(int matSemestre) {
        this.matSemestre = matSemestre;
    }


    @Column(name="cod_carrera", nullable=false)
    public int getCodCarrera() {
        return this.codCarrera;
    }
    
    public void setCodCarrera(int codCarrera) {
        this.codCarrera = codCarrera;
    }


    @Column(name="usu_rut", nullable=false)
    public int getUsuRut() {
        return this.usuRut;
    }
    
    public void setUsuRut(int usuRut) {
        this.usuRut = usuRut;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return (this.getMatAño()==castOther.getMatAño())
 && (this.getMatSemestre()==castOther.getMatSemestre())
 && (this.getCodCarrera()==castOther.getCodCarrera())
 && (this.getUsuRut()==castOther.getUsuRut());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMatAño();
         result = 37 * result + this.getMatSemestre();
         result = 37 * result + this.getCodCarrera();
         result = 37 * result + this.getUsuRut();
         return result;
   }   


}


