package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProgramacionProfesorId generated by hbm2java
 */
@Embeddable
public class ProgramacionProfesorId  implements java.io.Serializable {


     private int proAño;
     private int proSemestre;
     private int proParalelo;
     private int codAsign;
     private int usuRut;

    public ProgramacionProfesorId() {
    }

    public ProgramacionProfesorId(int proAño, int proSemestre, int proParalelo, int codAsign, int usuRut) {
       this.proAño = proAño;
       this.proSemestre = proSemestre;
       this.proParalelo = proParalelo;
       this.codAsign = codAsign;
       this.usuRut = usuRut;
    }
   


    @Column(name="pro_año", nullable=false)
    public int getProAño() {
        return this.proAño;
    }
    
    public void setProAño(int proAño) {
        this.proAño = proAño;
    }


    @Column(name="pro_semestre", nullable=false)
    public int getProSemestre() {
        return this.proSemestre;
    }
    
    public void setProSemestre(int proSemestre) {
        this.proSemestre = proSemestre;
    }


    @Column(name="pro_paralelo", nullable=false)
    public int getProParalelo() {
        return this.proParalelo;
    }
    
    public void setProParalelo(int proParalelo) {
        this.proParalelo = proParalelo;
    }


    @Column(name="cod_asign", nullable=false)
    public int getCodAsign() {
        return this.codAsign;
    }
    
    public void setCodAsign(int codAsign) {
        this.codAsign = codAsign;
    }


    @Column(name="usu_rut", nullable=false)
    public int getUsuRut() {
        return this.usuRut;
    }
    
    public void setUsuRut(int usuRut) {
        this.usuRut = usuRut;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProgramacionProfesorId) ) return false;
		 ProgramacionProfesorId castOther = ( ProgramacionProfesorId ) other; 
         
		 return (this.getProAño()==castOther.getProAño())
 && (this.getProSemestre()==castOther.getProSemestre())
 && (this.getProParalelo()==castOther.getProParalelo())
 && (this.getCodAsign()==castOther.getCodAsign())
 && (this.getUsuRut()==castOther.getUsuRut());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProAño();
         result = 37 * result + this.getProSemestre();
         result = 37 * result + this.getProParalelo();
         result = 37 * result + this.getCodAsign();
         result = 37 * result + this.getUsuRut();
         return result;
   }   


}


