package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProgramacionProfesor generated by hbm2java
 */
@Entity
@Table(name="programacion_profesor"
    ,catalog="navegadorcitodb"
)
public class ProgramacionProfesor  implements java.io.Serializable {


     private ProgramacionProfesorId id;

    public ProgramacionProfesor() {
    }

    public ProgramacionProfesor(ProgramacionProfesorId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="proAño", column=@Column(name="pro_año", nullable=false) ), 
        @AttributeOverride(name="proSemestre", column=@Column(name="pro_semestre", nullable=false) ), 
        @AttributeOverride(name="proParalelo", column=@Column(name="pro_paralelo", nullable=false) ), 
        @AttributeOverride(name="codAsign", column=@Column(name="cod_asign", nullable=false) ), 
        @AttributeOverride(name="usuRut", column=@Column(name="usu_rut", nullable=false) ) } )
    public ProgramacionProfesorId getId() {
        return this.id;
    }
    
    public void setId(ProgramacionProfesorId id) {
        this.id = id;
    }




}


