package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPerfil generated by hbm2java
 */
@Entity
@Table(name="tipo_perfil"
    ,catalog="navegadorcitodb"
)
public class TipoPerfil  implements java.io.Serializable {


     private int codPerfil;
     private String nomPerfil;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoPerfil() {
    }

	
    public TipoPerfil(int codPerfil, String nomPerfil) {
        this.codPerfil = codPerfil;
        this.nomPerfil = nomPerfil;
    }
    public TipoPerfil(int codPerfil, String nomPerfil, Set<Usuario> usuarios) {
       this.codPerfil = codPerfil;
       this.nomPerfil = nomPerfil;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="cod_perfil", unique=true, nullable=false)
    public int getCodPerfil() {
        return this.codPerfil;
    }
    
    public void setCodPerfil(int codPerfil) {
        this.codPerfil = codPerfil;
    }

    
    @Column(name="nom_perfil", nullable=false, length=20)
    public String getNomPerfil() {
        return this.nomPerfil;
    }
    
    public void setNomPerfil(String nomPerfil) {
        this.nomPerfil = nomPerfil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPerfil")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


