package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="navegadorcitodb"
)
public class Usuario  implements java.io.Serializable {


     private int usuRut;
     private TipoPerfil tipoPerfil;
     private String usuDv;
     private String usuNombre;
     private String usuPaterno;
     private String usuMaterno;
     private String direccion;
     private String correo;
     private String clave;

    public Usuario() {
    }

    public Usuario(int usuRut, TipoPerfil tipoPerfil, String usuDv, String usuNombre, String usuPaterno, String usuMaterno, String direccion, String correo, String clave) {
       this.usuRut = usuRut;
       this.tipoPerfil = tipoPerfil;
       this.usuDv = usuDv;
       this.usuNombre = usuNombre;
       this.usuPaterno = usuPaterno;
       this.usuMaterno = usuMaterno;
       this.direccion = direccion;
       this.correo = correo;
       this.clave = clave;
    }
   
     @Id 

    
    @Column(name="usu_rut", unique=true, nullable=false)
    public int getUsuRut() {
        return this.usuRut;
    }
    
    public void setUsuRut(int usuRut) {
        this.usuRut = usuRut;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_perfil", nullable=false)
    public TipoPerfil getTipoPerfil() {
        return this.tipoPerfil;
    }
    
    public void setTipoPerfil(TipoPerfil tipoPerfil) {
        this.tipoPerfil = tipoPerfil;
    }

    
    @Column(name="usu_dv", nullable=false, length=1)
    public String getUsuDv() {
        return this.usuDv;
    }
    
    public void setUsuDv(String usuDv) {
        this.usuDv = usuDv;
    }

    
    @Column(name="usu_nombre", nullable=false, length=20)
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }

    
    @Column(name="usu_paterno", nullable=false, length=20)
    public String getUsuPaterno() {
        return this.usuPaterno;
    }
    
    public void setUsuPaterno(String usuPaterno) {
        this.usuPaterno = usuPaterno;
    }

    
    @Column(name="usu_materno", nullable=false, length=20)
    public String getUsuMaterno() {
        return this.usuMaterno;
    }
    
    public void setUsuMaterno(String usuMaterno) {
        this.usuMaterno = usuMaterno;
    }

    
    @Column(name="direccion", nullable=false, length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="correo", nullable=false, length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="clave", nullable=false, length=20)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }



}


