package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name="asignatura"
    ,catalog="navegadorcitodb"
)
public class Asignatura  implements java.io.Serializable {


     private int codAsign;
     private String nomAsign;
     private String sigla;

    public Asignatura() {
    }

    public Asignatura(int codAsign, String nomAsign, String sigla) {
       this.codAsign = codAsign;
       this.nomAsign = nomAsign;
       this.sigla = sigla;
    }
   
     @Id 

    
    @Column(name="cod_asign", unique=true, nullable=false)
    public int getCodAsign() {
        return this.codAsign;
    }
    
    public void setCodAsign(int codAsign) {
        this.codAsign = codAsign;
    }

    
    @Column(name="nom_asign", nullable=false, length=100)
    public String getNomAsign() {
        return this.nomAsign;
    }
    
    public void setNomAsign(String nomAsign) {
        this.nomAsign = nomAsign;
    }

    
    @Column(name="sigla", nullable=false, length=50)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }




}


