package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CarreraEstudiante generated by hbm2java
 */
@Entity
@Table(name="carrera_estudiante"
    ,catalog="navegadorcitodb"
)
public class CarreraEstudiante  implements java.io.Serializable {


     private CarreraEstudianteId id;

    public CarreraEstudiante() {
    }

    public CarreraEstudiante(CarreraEstudianteId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codCarrera", column=@Column(name="cod_carrera", nullable=false) ), 
        @AttributeOverride(name="usuRut", column=@Column(name="usu_rut", nullable=false) ) } )
    public CarreraEstudianteId getId() {
        return this.id;
    }
    
    public void setId(CarreraEstudianteId id) {
        this.id = id;
    }




}


