package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name="carrera"
    ,catalog="navegadorcitodb"
)
public class Carrera  implements java.io.Serializable {


     private int codCarrera;
     private String nomCarrera;

    public Carrera() {
    }

    public Carrera(int codCarrera, String nomCarrera) {
       this.codCarrera = codCarrera;
       this.nomCarrera = nomCarrera;
    }
   
     @Id 

    
    @Column(name="cod_carrera", unique=true, nullable=false)
    public int getCodCarrera() {
        return this.codCarrera;
    }
    
    public void setCodCarrera(int codCarrera) {
        this.codCarrera = codCarrera;
    }

    
    @Column(name="nom_carrera", nullable=false, length=100)
    public String getNomCarrera() {
        return this.nomCarrera;
    }
    
    public void setNomCarrera(String nomCarrera) {
        this.nomCarrera = nomCarrera;
    }




}


