package POJOS;
// Generated 05-09-2017 9:28:14 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MallaCurricular generated by hbm2java
 */
@Entity
@Table(name="malla_curricular"
    ,catalog="navegadorcitodb"
)
public class MallaCurricular  implements java.io.Serializable {


     private MallaCurricularId id;
     private int añoMalla;
     private String vigente;

    public MallaCurricular() {
    }

    public MallaCurricular(MallaCurricularId id, int añoMalla, String vigente) {
       this.id = id;
       this.añoMalla = añoMalla;
       this.vigente = vigente;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codPlan", column=@Column(name="cod_plan", nullable=false) ), 
        @AttributeOverride(name="codCarrera", column=@Column(name="cod_carrera", nullable=false) ), 
        @AttributeOverride(name="codAsign", column=@Column(name="cod_asign", nullable=false) ) } )
    public MallaCurricularId getId() {
        return this.id;
    }
    
    public void setId(MallaCurricularId id) {
        this.id = id;
    }

    
    @Column(name="año_malla", nullable=false)
    public int getAñoMalla() {
        return this.añoMalla;
    }
    
    public void setAñoMalla(int añoMalla) {
        this.añoMalla = añoMalla;
    }

    
    @Column(name="vigente", nullable=false, length=20)
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }




}


